name: Integration Pipeline
on:
  workflow_dispatch:
  pull_request:
    branches: [develop, main]

concurrency:
  group: build-${{ github.ref || github.run_id }}

jobs:
  integration_pipeline:
    name: integration_pipeline
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "build.sh"
        run: |
          ./tests/build/build.sh
        shell: bash

      - name: "Test"
        run: |
          cd tests/build
          ctest
        shell: bash
